#!/bin/sh

TRACING_DIR='/sys/kernel/debug/tracing'

cd ${TRACING_DIR}

# Disable tracing and clear the trace
echo 0 > tracing_on
echo 0 > events/enable 
echo > trace

# Configure function tracer
echo function_graph > current_tracer
echo > set_ftrace_filter
echo "*taudac*" >> set_ftrace_filter
echo "*si5351*" >> set_ftrace_filter
echo "*wm8741*" >> set_ftrace_filter
cat set_ftrace_filter

# Configure Clock, I2C, and GPIO event tracers
echo 1 > events/clk/enable
echo 1 > events/i2c/enable
echo 1 > events/gpio/gpio_value/enable
echo "!gpio==29" >> events/gpio/gpio_value/filter
cat events/gpio/gpio_value/filter

# Enable tracing
echo 1 > tracing_on

# vim: ts=2 sw=2 et
